version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - "0.0.0.0:9092"
      - --advertise-kafka-addr
      - "redpanda:9092"
    ports:
      - "9092:9092"   # outside Kafka API
      - "9644:9644"   # admin API

  topic-init:
    image: redpandadata/redpanda:latest
    depends_on: [redpanda]
    restart: "no"
    entrypoint: ["/bin/sh","-lc"]
    command: >
      rpk cluster wait --brokers=redpanda:9092 &&
      rpk topic create image-deleted -p 1 -r 1 --brokers=redpanda:9092 || true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  image-processing-api:
    build:
      context: .
      dockerfile: image-processing-api/Dockerfile
    image: gardrops/image-processing-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      STORAGE_BASEPATH: /data/images
      SECURITY_LOCALHOST_ONLY_ENABLED: "true"
      SECURITY_LOCALHOST_ONLY_ALLOW_PRIVATE: "true"
      SECURITY_LOCALHOST_ONLY_ALLOWED_CIDRS: "172.17.0.0/16"
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      APP_TOPICS_IMAGE_DELETED: image-deleted
    volumes:
      - ./data/images:/data/images
    expose:
      - "8081"
    depends_on:
      - redis
      - redpanda
      - topic-init

  image-upload-api:
    build:
      context: .
      dockerfile: image-upload-api/Dockerfile
    image: gardrops/image-upload-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_URL: redis://redis:6379/0
      # SPRING_DATA_REDIS_HOST: redis
      # SPRING_DATA_REDIS_PORT: 6379

      GARDROPS_PROCESSING_BASEURL: http://image-processing-api:8081
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      APP_TOPICS_IMAGE_DELETED: image-deleted
    ports:
      - "8080:8080"
    depends_on:
      - image-processing-api
      - redis
      - redpanda
      - topic-init
